export type sellerDisclosureModel = {
  propertyId?: string;
  legalAuthority?: "YES" | "NO" | "UNKNOWN";
  yearsOwned?: number;
  monthsOwned?: number;
  isOccupied?: "YES" | "NO" | "UNKNOWN";
  hasSellerOccupied?: "YES" | "NO" | "UNKNOWN";
  isRented?: "YES" | "NO" | "UNKNOWN";
  leaseExpiration?: Date;
  hasHOA?: "YES" | "NO" | "UNKNOWN";
  hasHOAViolations?: "YES" | "NO" | "UNKNOWN";
  hasCCAndRs?: "YES" | "NO" | "UNKNOWN";
  isHistoric?: "YES" | "NO" | "UNKNOWN";
  hasOtherRestrictions?: "YES" | "NO" | "UNKNOWN";
  otherRestrictionsText?: string;
  hasEncroachmentsOrBoundaryDisputes?: "YES" | "NO" | "UNKNOWN";
  hasEasements?: "YES" | "NO" | "UNKNOWN";
  hasZoningCodeViolations?: "YES" | "NO" | "UNKNOWN";
  hasDeedRestrictions?: "YES" | "NO" | "UNKNOWN";
  sellerHasLeins?: "YES" | "NO" | "UNKNOWN";
  hasLawsuitsOrLeins?: "YES" | "NO" | "UNKNOWN";
  hasInsuranceClaims?: "YES" | "NO" | "UNKNOWN";
  insuranceClaimsText?: string;
  hasGovernmentNotices?: "YES" | "NO" | "UNKNOWN";
  isAgricultural?: "YES" | "NO" | "UNKNOWN";
  hasKnownAdverseTitleConditions?: "YES" | "NO" | "UNKNOWN";
  adverseTitleConditionsText?: string;
  servicePanelState?: "WORKING" | "NOT WORKING" | "UNKNOWN";
  naturalGasState?: "WORKING" | "NOT WORKING" | "UNKNOWN";
  hasNatGasFurnace?: boolean;
  hasNatGasWaterHeater?: boolean;
  hasNatGasStove?: boolean;
  hasNatGasFireplace?: boolean;
  securitySystemState?: "WORKING" | "NOT WORKING" | "UNKNOWN";
  securitySystemOwned?: boolean;
  smokeDetectorsState?: "WORKING" | "NOT WORKING" | "UNKNOWN";
  carbonMonoxideDetectorsState?: "WORKING" | "NOT WORKING" | "UNKNOWN";
  garageDoorState?: "WORKING" | "NOT WORKING" | "UNKNOWN";
  garageDoorOpenerType?: "OPENER" | "REMOTE" | "KEYPAD";
  electricalExtraInfo?: string;
  presentDamageRoof?: "YES" | "NO" | "UNKNOWN";
  yearsOldRoof?: number;
  roofRepairs?: "YES" | "NO" | "UNKNOWN";
  waterDamage?: "YES" | "NO" | "UNKNOWN";
  waterDamageDate?: Date;
  waterDamageLocation?: string;
  waterDamageRepairs?: "YES" | "NO" | "UNKNOWN";
  fireWindDamage?: "YES" | "NO" | "UNKNOWN";
  fireWindDamageDate?: Date;
  fireWindDamageLocation?: string;
  fireWindDamageRepairs?: "YES" | "NO" | "UNKNOWN";
  windowsWorkable?: "YES" | "NO" | "UNKNOWN";
  foundationDamage?: "YES" | "NO" | "UNKNOWN";
  floorsDamage?: "YES" | "NO" | "UNKNOWN";
  wallsDamage?: "YES" | "NO" | "UNKNOWN";
  drivewayDamage?: "YES" | "NO" | "UNKNOWN";
  balconyDamage?: "YES" | "NO" | "UNKNOWN";
  sidingDamage?: "YES" | "NO" | "UNKNOWN";
  exteriorWallsDamage?: "YES" | "NO" | "UNKNOWN";
  improvementsWithPermits?: "YES" | "NO" | "UNKNOWN";
  concealedDefects?: "YES" | "NO" | "UNKNOWN";
  structureExtraInfo?: string;
  hasHVAC?: "YES" | "NO" | "UNKNOWN";
  hvacNeedsRepair?: "YES" | "NO" | "UNKNOWN";
  hvacInstalled?: Date;
  hvacLastServiced?: Date;
  hasHeatingSystem?: "YES" | "NO" | "UNKNOWN";
  heatingNeedsRepair?: "YES" | "NO" | "UNKNOWN";
  heatingInstalled?: Date;
  heatingLastServiced?: Date;
  fireplaceFunctioning?: "YES" | "NO" | "UNKNOWN";
  fireplaceLastServiced?: Date;
  partOfHomeNoHVAC?: "YES" | "NO" | "UNKNOWN";
  partOfHomeNoHVACDescription?: string;
  hvacExtraInfo?: string;
  hasPublicSewer?: "YES" | "NO" | "UNKNOWN";
  publicSewerFunctional?: "YES" | "NO" | "UNKNOWN";
  hasSepticSystem?: "YES" | "NO" | "UNKNOWN";
  septicSystemFunctional?: "YES" | "NO" | "UNKNOWN";
  septicSystemMeetsMinRequirements?: "YES" | "NO" | "UNKNOWN";
  septicSystemLastServiced?: Date;
  hasPrivateSewer?: "YES" | "NO" | "UNKNOWN";
  privateSewerFunctional?: "YES" | "NO" | "UNKNOWN";
  hasPumpSump?: "YES" | "NO" | "UNKNOWN";
  pumpSumpDischarge?: string;
  plumbingIssues?: "YES" | "NO" | "UNKNOWN";
  wellSystem?: "YES" | "NO" | "UNKNOWN";
  wellSystemNeedsRepar?: "YES" | "NO" | "UNKNOWN";
  wellSystemWaterLastTested?: Date;
  notifiedOfWellWaterIssues?: "YES" | "NO" | "UNKNOWN";
  waterHeaterFunctional?: "YES" | "NO" | "UNKNOWN";
  waterHeaterInstalled?: Date;
  sewerLineIssues?: "YES" | "NO" | "UNKNOWN";
  waterLinesFrozenOrDamaged?: "YES" | "NO" | "UNKNOWN";
  installedSprinklerSystem?: "YES" | "NO" | "UNKNOWN";
  sprinklerSystemNeedsRepair?: "YES" | "NO" | "UNKNOWN";
  propertyContainsPolybutylenePiping?: "YES" | "NO" | "UNKNOWN";
  additionalPlumbingInfo?: string;
  wasConstructedBefore1978?: "YES" | "NO" | "UNKNOWN";
  knownLeadPaint?: boolean;
  leadPaintExtraInfo?: string;
  leadBasedPaintReports?: boolean;
  leadBasedPaintReportsExtraInfo?: string;
  hasAsbestos?: "YES" | "NO" | "UNKNOWN";
  hasRadon?: "YES" | "NO" | "UNKNOWN";
  hasMold?: "YES" | "NO" | "UNKNOWN";
  hasContaminatedSoil?: "YES" | "NO" | "UNKNOWN";
  trashDumpNearby?: "YES" | "NO" | "UNKNOWN";
  undergroundFuelOrChemicalStorageTank?: "YES" | "NO" | "UNKNOWN";
  hasMethtamphetamine?: "YES" | "NO" | "UNKNOWN";
  inFloodPlain?: "YES" | "NO" | "UNKNOWN";
  gradingFloodingOrDrainageIssues?: "YES" | "NO" | "UNKNOWN";
  hasUndergroundSprings?: "YES" | "NO" | "UNKNOWN";
  hasSoilMovement?: "YES" | "NO" | "UNKNOWN";
  environmentalExtraInfo?: string;
  infestationDamage?: "YES" | "NO" | "UNKNOWN";
  underPestControlWarranty?: "YES" | "NO" | "UNKNOWN";
  petsOrAnimals?: "YES" | "NO" | "UNKNOWN";
  damagedOrDiseasedTrees?: "YES" | "NO" | "UNKNOWN";
  pestExtraInfo: string;
  ovenStoveRemains?: boolean;
  rangeRemains?: boolean;
  rangeVentilatorRemains?: boolean;
  cooktopRemains?: boolean;
  refrigeratorRemains?: boolean;
  freezerRemains?: boolean;
  microwaveOvenRemains?: boolean;
  builtInVacuumSystemRemains?: boolean;
  iceMakerRemains?: boolean;
  dishwasherRemains?: boolean;
  wineCoolerRemains?: boolean;
  garbageDisposalRemains?: boolean;
  trashCompactorRemains?: boolean;
  washingMachineRemains?: boolean;
  clothesDryerRemains?: boolean;
  securityCameraRemains?: boolean;
  alarmSystemsRemains?: boolean;
  smokeDetectorRemains?: boolean;
  carbonMonoxideRemains?: boolean;
  windowScreensRemains?: boolean;
  windowSecurityGateRemains?: boolean;
  doorLocksRemains?: boolean;
  fireSprinklerSystemRemains?: boolean;
  solarPanelsRemains?: boolean;
  carChargingStationRemains?: boolean;
  airConditionerUnitRemains?: boolean;
  airPurifierRemains?: boolean;
  atticFanRemains?: boolean;
  generatorRemains?: boolean;
  humidifierRemains?: boolean;
  dehumidifierRemains?: boolean;
  hotTubRemains?: boolean;
  waterPurifierRemains?: boolean;
  waterSoftenerRemains?: boolean;
  propaneTankRemains?: boolean;
  fuelOilTankRemains?: boolean;
  wellPumpRemains?: boolean;
  sumpPumpRemains?: boolean;
  seweragePumpRemains?: boolean;
  windowBlindsRemains?: boolean;
  windowCurtainsRemains?: boolean;
  windowShuttersRemains?: boolean;
  windowHardwareRemains?: boolean;
  ceilingFansRemains?: boolean;
  lightFixturesRemains?: boolean;
  shelvingSystemsRemains?: boolean;
  storageSystemsRemains?: boolean;
  closetSystemsRemains?: boolean;
  fireplaceRemains?: boolean;
  fireplaceAccessoriesRemains?: boolean;
  mirrorRemains?: boolean;
  showerheadRemains?: boolean;
  builtInSafeRemains?: boolean;
  gasGrillRemains?: boolean;
  outdoorFurnitureRemains?: boolean;
  poolAndEquipmentRemains?: boolean;
  saunaRemains?: boolean;
  outdoorKitchenRemains?: boolean;
  basketballSystemRemains?: boolean;
  kidsPlaySystemRemains?: boolean;
  doghouseRemains?: boolean;
  storageBuildingRemains?: boolean;
  swingRemains?: boolean;
  gazeboRemains?: boolean;
  outdoorLightingRemains?: boolean;
  arborRemains?: boolean;
  mailboxRemains?: boolean;
  otherSystemOne?: string;
  otherSystemTwo?: string;
  otherSystemThree?: string;
  otherSystemFour?: string;
  otherSystemFive?: string;
  otherSystemSix?: string;
  otherSystemSeven?: string;
  createdAt?: Date;
  updatedAt?: Date;
};
